# generate a github action workflow that invoked builds/generate.sh on any push, and commits the changes to the repo
name: Regenerate Lua
on:
  workflow_dispatch:
  push:
    paths:
      - 'background/*'
      - 'border/*'
      - 'font/*'
      - 'sound/*'
      - 'statusbar/*'

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
        - uses: actions/checkout@v3
          with:
            ref: ${{ github.head_ref }}
        - name: Generate Lua
          run: |
            cat MyMedia.lua
            ./.build/generate.sh
            cat MyMedia.lua
        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Regenerated Lua
