# generate a github action workflow that invoked builds/generate.sh on any push, and commits the changes to the repo
name: Regenerate Lua
on:
  workflow_dispatch:
  push:
    paths:
      - 'background/*'
      - 'border/*'
      - 'font/*'
      - 'sound/*'
      - 'statusbar/*'

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
        - uses: actions/checkout@v3
          with:
            ref: ${{ github.head_ref }}

        - name: Generate Lua
          run: |
            cat MyMedia.lua
            cd .build
            ./generate.sh
            cd ..
            cat MyMedia.lua

        - uses: stefanzweifel/git-auto-commit-action@v4
          id: commit
          with:
            commit_message: Regenerated Lua

        - name: Bump version and push tag
          id: tag_version
          uses: mathieudutour/github-tag-action@v6.1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            commit_sha: ${{ steps.commit.outputs.commit_hash }}

        - name: Create a GitHub release
          uses: ncipollo/release-action@v1
          with:
            tag: ${{ steps.tag_version.outputs.new_tag }}
            name: Release ${{ steps.tag_version.outputs.new_tag }}
            body: ${{ steps.tag_version.outputs.changelog }}